default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  schema_search_path: public
  min_messages: notice


development:
  <<: *default
  database: credify_development

test:
  <<: *default
  database: credify_test

production:
  primary: &primary_production
    <<: *default
    database: credify_production
  cache:
    <<: *primary_production
    database: credify_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: credify_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: credify_production_cable
    migrations_paths: db/cable_migrate
